<Project Sdk="RaptorRush135.PvZR.Sdk">

  <PropertyGroup>
    <IsModBuild>true</IsModBuild>
    <ModMelonType>$(RootNamespace).Core</ModMelonType>
    <ModColor>255, 220, 40, 40</ModColor>
  </PropertyGroup>

  <PropertyGroup>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerDefaultPreReleaseIdentifiers>dev</MinVerDefaultPreReleaseIdentifiers>
  </PropertyGroup>

  <Target Name="DisableZipVersionDotReplacementForPreRelease" AfterTargets="MinVer" Condition="'$(MinVerPreRelease)' != ''">
    <PropertyGroup>
      <ModZipReplaceVersionDots>false</ModZipReplaceVersionDots>
    </PropertyGroup>
  </Target>

  <ItemGroup>
    <EmbeddedResource Include="Assets/SkinSwap.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Common\**\*.cs" Exclude="**\obj\**" Link="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>