<Project>

  <PropertyGroup>
    <ModAuthor>RaptorRush</ModAuthor>
    <ModDownloadLink>https://github.com/RaptorRush135/PvZRSkinPicker</ModDownloadLink>
  </PropertyGroup>

  <PropertyGroup>
    <IsModBuild>false</IsModBuild>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ModEnvironmentReference Include="Newtonsoft.Json.dll" />
    <ModEnvironmentReference Include="System.Diagnostics.DiagnosticSource.dll" />
    <ModEnvironmentReference Include="Microsoft.Extensions.Logging.Abstractions.dll" />
    <ModEnvironmentReference Include="Microsoft.Extensions.DependencyInjection.Abstractions.dll" />
  </ItemGroup>

</Project>
